---
- name: influxdb - create folders
  file: path=~/rpm state=directory mode=0755

- name: influxdb - check if sources have been downloaded
  stat: path=~/rpm/{{ INFLUXDB_RPM_FILENAME }}
  register: influxdb_download

- name: influxdb - download sources
  shell: wget http://s3.amazonaws.com/influxdb/{{ INFLUXDB_RPM_FILENAME }}
  when: not influxdb_download.stat.exists
  args:
    chdir: ~/rpm

- name: influxdb - install
  yum: name=/{{ ansible_env.HOME}}/rpm/{{ INFLUXDB_RPM_FILENAME }} state=present

- name: influxdb - copy config
  template: src=influxdb.conf dest=/etc/influxdb/influxdb.conf

- name: influxdb - start service
  service: name=influxdb state=started

- name: influxdb - wait for service
  wait_for: port=8086 delay=2

# created by collectd plugin conf
- name: influxdb - create grafana database
  shell: "influx -execute 'CREATE DATABASE {{ INFLUXDB_DATABASE }}'"

- name: influxdb - create project user
  shell: "influx -execute \"CREATE USER {{ INFLUXDB_USER }} WITH PASSWORD '{{ INFLUXDB_PASSWORD }}'\""

- name: influxdb - create grafana user
  shell: "influx -execute \"CREATE USER grafana WITH PASSWORD '{{ INFLUXDB_GRAFANA_PASSWORD }}'\""

- name: influxdb - create admin user
  shell: "influx -execute \"CREATE USER root WITH PASSWORD '{{ INFLUXDB_ROOT_PASSWORD }}' WITH ALL PRIVILEGES\""
