---
- name: grafana - create folders
  file: path=~/rpm state=directory mode=0755

- name: grafana - check if rpms have been downloaded
  stat: path=~/rpm/{{ GRAFANA_RPM_FILENAME }}
  register: grafana_download

- name: grafana - download rpms
  shell: wget http://grafanarel.s3.amazonaws.com/builds/{{ GRAFANA_RPM_FILENAME }}
  when: not grafana_download.stat.exists
  args:
    chdir: ~/rpm

#- name: grafana - install deps
#  shell: "yum install -y initscripts fontconfig"

- name: grafana - install
  yum: name=/{{ ansible_env.HOME}}/rpm/{{ GRAFANA_RPM_FILENAME }} state=present

- name: grafana - reload systemd
  shell: "systemctl daemon-reload"

- name: gragana - start service
  service: name=grafana-server state=started
