---
- name: server-metrics - install python-dev
  yum: name=python-devel state=present

- name: server-metrics - install pip
  yum: name=python-pip state=present

- name: server-metrics - update pip
  pip: name=pip extra_args="--upgrade"

- name: server-metrics - install git
  yum: name=git-core state=present

- name: server-metrics - clone repo
  git: repo=https://github.com/bitmazk/python-server-metrics-scripts dest=/opt/python-server-metrics-scripts

- name: server-metrics - install requirements
  pip: requirements=/opt/python-server-metrics-scripts/requirements.txt
